### ISSUE TITLE
Gallery folders not being created

### ISSUE THREAD

**Issue by davidpede** [modxcms/Gallery#20]
When uploading to a new album I receive the following error:

```
[2014-03-20 16:09:00] (ERROR @ /assets/components/gallery/connector.php) [Gallery] Could not create directory (possibly already exists?): img/gallery/65/
```

Gallery doesn't create the '65' folder. Permissions are correct. If I manually create the 65 folder via ftp, gallery will work as normal.

Using MODX 2.2.13, Gallery 1.6.2-beta1

Settings:
gallery.files_path: /img/gallery/
gallery.files_url: /img/gallery/

Please see: http://forums.modx.com/thread/89700/gallery-modx-2-2-13-and-thumbnails#dis-post-493201

**Comment by RoelS7** [comment]
Is there any solution to it? 

Looks like I'm having the same problem with MODX Revolution 2.5.7-pl en Gallery 1.7.0-pl. Can't seem to find a solution. Every time I want to upload a picture, the gallery generates an upload folder like C:\fakepath\image.jpg. I think the problem is over there? 

I'm not an expert in coding, but I want to solve the problem for my client. He can't upload new pictures anymore to the gallery on his website.
