### ISSUE TITLE
Updated to Gallery 1.7 on MODX 2.3.1 and thumbnails stopped working

### ISSUE THREAD

**Issue by ricardo-lewis** [modxcms/Gallery#48]
Both in the actual Gallery Component admin interface (grid view) and also on the front end. 

The connector at **assets/components/gallery/connector.php** returns an empty response, but it's an HTTP 200 OK, so I don't have an error to chase down.

Luckily, I have a hot-fixed version of 1.6.1 that works fine in MODX 2.3.

**Comment by exside** [comment]
@ricardo-lewis is it possible that you updated from a fairly old version of Gallery? I'm just fixing the same problem on a 2.2.16 instance, the problem is that gallery changed the way files are handled and thus cannot find the files anymore that were uploaded in an older version (at least in my case that's the problem)...

**Comment by ricardo-lewis** [comment]
So the solution is to not upgrade if you're on an older version?
